### ISSUE TITLE
API for error already extracted from stats

### ISSUE THREAD

**Issue by davidtheclark** [lukeed/webpack-format-messages#2]
What would you think about exposing the `formatMessage` function as public API, so users can format error messages that are already extracted from the stats object?

**Comment by lukeed** [comment]
Hey, what's the need for this? Are you doing some heavy customization & just want the cleanup?

> Btw, have you seen [`webpack-messages`](https://github.com/lukeed/webpack-messages)?

**Comment by davidtheclark** [comment]
I will try webpack-messages, see if that does the trick.

> Are you doing some heavy customization & just want the cleanup?

Yep, that's the situation.

**Comment by lukeed** [comment]
Okay, keep me posted 👍 

Wouldn't mind exposing as a public function, but would prefer not to if don't have to~

**Comment by davidtheclark** [comment]
That plugin is very cool! But a little too comprehensive for my use-case, I guess (I'm already messing with the logging).

> would prefer not to if don't have to

You certainly don't have to if you don't want to! I can close the issue since you'd prefer not to. 

Thanks for your response!

**Comment by lukeed** [comment]
It won't hurt. 😉

**Comment by davidtheclark** [comment]
Thanks!
