### ISSUE TITLE
Webpack 4 - Tapable.plugin is deprecated

### ISSUE THREAD

**Issue by bastienrobert** [lukeed/webpack-format-messages#4]
I'm using `webpack-format-messages` for my personal starter but, and I think it's because of webpack 4, i'm trying to set it up, an error is shown in the console:
```
(node:66961) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

Then, with your example using the API in the README, the message is staying at `compiling...` and it's never going to `Compiled successfully!`

**Comment by lukeed** [comment]
Hey,  #5 updated the README which means this can technically be closed.

Sorry for the delay in response – I hope you were able to figure it out! If not, you could look at [`webpack-messages`](https://github.com/lukeed/webpack-messages/blob/master/index.js#L45-L53) which uses this plugin & supports both Webpack 3 & 4.

Thanks!
